services:
  webapp:
    image: gymsaas-web
    container_name: gymsaas_app
    build:
      context: .
      dockerfile: src/GymSaaS.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Construimos la cadena de conexion usando las variables del .env
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      # Variables de seguridad que agregamos antes
      - MercadoPago__AccessToken=${MP_ACCESS_TOKEN}
      - Security__EncryptionKey=${SECURITY_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gym-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gymsaas_db
    environment:
      - ACCEPT_EULA=Y
      # Inyectamos la contrasena desde el .env
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - gym-network
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      # El Healthcheck tambien usa las variables para probar la conexion
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U ${DB_USER} -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  gym-network:
    driver: bridge

volumes:
  sql_data: